name: execute testorials            # (1)

on:                                 # (2)
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:                # (3)

jobs:
  run-clitest:
    runs-on: ubuntu-latest          # (4)

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install clitest
      run: |
         curl -sOL https://raw.githubusercontent.com/aureliojargas/clitest/master/clitest
         chmod +x clitest

    - name: Run clitest on your testorial-
      run: ./clitest --prefix '@learner ' ./docs/hello_world.md.html
